[project]
name = "ComfyUI"
version = "0.3.35"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "comfyui-frontend-package==1.20.4",
    "comfyui-workflow-templates==0.1.18",
    "torchsde",
    "numpy>=1.25.0",
    "einops",
    "transformers>=4.28.1",
    "tokenizers>=0.13.3",
    "sentencepiece",
    "safetensors>=0.4.2",
    "aiohttp>=3.11.8",
    "pyyaml",
    "yarl>=1.18.0",
    "Pillow",
    "scipy",
    "tqdm",
    "psutil",
    "av>=14.2.0",
    "pydantic~=2.0",
    # Optional dependencies
    "kornia>=0.7.1",
    "spandrel",
    "soundfile",
    # common custom node deps
    "opencv-python",
    "accelerate>=1.1.1",
    "diffusers>=0.31.0",
    "scikit-image",
    "torchtyping",
    "numba",
    "colour-science",
    "rembg",
    "transparent-background",
]

[project.optional-dependencies]
# ---------- custom node deps ----------
mvadapter = [
    "peft",
    "omegaconf", 
    "trimesh", 
    "timm", 
]

hunyuan3dwrapper = [
    "xatlas",
    "pymeshlab",
    "pygltflib",
    "scikit-learn",
    "pybind11",
    "custom-rasterizer==0.1.0+torch260.cuda126",
    # "utils3d",
    # "nvdiffrast",
    # #for quad remeshing node
    # "pynanoinstantmeshes",
    # #for fast decimation node
    # "pyfqmr",
    # "diso",
    # # ---------- hy3dgen shapegen bpt ----------
    "meshgpt_pytorch",
    "pytorch-custom-utils",
    "beartype",
    "classifier-free-guidance-pytorch",
    "ema-pytorch",
    "pytorch-warmup",
    "torch_geometric",
    "vector-quantize-pytorch",
    "x-transformers",
    "matplotlib",
    "wandb",
    "pyrr",
    "trimesh",
    "opencv-python",
    "pyrender",
    "open3d-python",
    "easydict",
    "chardet",
    "omegaconf",
    "scikit-image",
    "pytorch_lightning",
    "mesh2sdf",
    "point-cloud-utils",
    "networkx",
    # "deepspeed", # only for *nix

]

# ---------- TORCH ----------
cpu = [
  "torch",
  "torchvision",
  "torchaudio",
]

cu126 = [
  "torch",
  "torchvision",
  "torchaudio",
]

cu124 = [
  "torch",
  "torchvision",
  "torchaudio",
]

cu118 = [
  "torch",
  "torchvision",
  "torchaudio",
]

rocm = [
  "torch",
  "torchvision",
  "torchaudio",
]

xpus = [
  "torch",
  "torchvision",
  "torchaudio",
]

[tool.uv]
# Resolve for macOS, but not for Linux or Windows.
# environments = ["sys_platform == 'win32'"]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
    { extra = "cu124" },
    { extra = "cu118" },
    { extra = "rocm" },
    { extra = "xpus" },
  ],
  [
    { extra = "hunyuan3dwrapper" },
    { extra = "cpu" },
    { extra = "cu124"},
    { extra = "cu118" },
    { extra = "rocm" },
    { extra = "xpus" },
  ]
]

find-links = ["./custom_nodes/ComfyUI-Hunyuan3DWrapper/wheels/"]

[project.urls]
homepage = "https://www.comfy.org/"
repository = "https://github.com/comfyanonymous/ComfyUI"
documentation = "https://docs.comfy.org/"

[tool.ruff]
lint.select = [
  "N805", # invalid-first-argument-name-for-method
  "S307", # suspicious-eval-usage
  "S102", # exec
  "T",    # print-usage
  "W",
  # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
  # See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
  "F",
]
exclude = ["*.ipynb"]

[tool.uv.sources]
# ---------- TORCH ----------
torch = [
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu124", extra = "cu124" },
  { index = "pytorch-cu118", extra = "cu118" },
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-rocm", extra = "rocm" },
  { index = "pytorch-xpu", extra = "xpus" },
]
torchvision = [
    { index = "pytorch-cu126", extra = "cu126" },
    { index = "pytorch-cu124", extra = "cu124" },
    { index = "pytorch-cu118", extra = "cu118" },
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-rocm", extra = "rocm" },
    { index = "pytorch-xpu", extra = "xpus" },
]
torchaudio = [
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu124", extra = "cu124" },
  { index = "pytorch-cu118", extra = "cu118" },
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-rocm", extra = "rocm" },
  { index = "pytorch-xpu", extra = "xpus" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true